import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import Header from "./components/Header/Header";
export const metadata = {
  title: "Đề tài NCKH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex gap-5">
        <Sidebar />
        <div className="flex flex-col w-full gap-6">
          <Header />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
